### ISSUE TITLE
Training speed of new code is much slower than before

### ISSUE THREAD

**Issue by kapsl** [rail-berkeley/softlearning#124]
Hi,
till a few days ago I ran the softlearning code from ~ last July. Now i updated to the current version with TF 2.0 etc. 

As a result I see that training the same number of iterations is approx. 1/3 to 1/2 slower than before...

I created a version (of the old code), where the training runs in an extra thread. It seems like this also speeds up training, additionally. Are you interested in those changes?

**Comment by hartikainen** [comment]
Hey @kapsl, thanks for reporting this! I must've missed something because I did some testing with the tf2 changes before merging them in and couldn't see much of a difference in the performance (neither in terms of wall-clock time nor sample complexity). Sorry about that!

I have an open PR for properly updating things to tf2-style of code, i.e. getting rid of `tf.Session`s and `tf.placeholder`s etc. and using `tf.function`-decorators. I will make sure that the possible slowness gets fixed before that goes in.

Re threaded training run: do you mean that the gradient steps are running in an extra thread or that the environment sampling is running on an extra thread? I've been planning to add parallelizations especially for the environment sampling but haven't had time to implement much yet. Would love to see what you have done and see if there's something that could be incorporated into softlearning.

**Comment by kapsl** [comment]
Sampling and learning is running in extra threads. I can send you the code I have next week. Its for the old softlearning code, but I think it should be easy adaptable
