### ISSUE TITLE
why not support pip ?

### ISSUE THREAD

**Issue by starimpact** [rail-berkeley/softlearning#16]
how to let softleanring support pip install ?

**Comment by hartikainen** [comment]
We do support pip installation, since we use pip in our conda environments. If you want to manually install using pip, you can just run `pip install -r requirements.txt`. Make sure you're using python 3.6. You might also need to install some other dependencies (see the cpu [Dockerfile](https://github.com/rail-berkeley/softlearning/blob/master/docker/Dockerfile.softlearning.base.cpu#L41) for example).

**Comment by starimpact** [comment]
ok, i will have a try.
