### ISSUE TITLE
Incompatible with tensorflow 2.4.0

### ISSUE THREAD

**Issue by xanderdunn** [rail-berkeley/softlearning#170]
setup.py lists its tensorflow dependency as `tensorflow>=2.2.0`, which currently installs tensorflow 2.4.0. 

Running this:
```
softlearning run_example_local examples.development \
    --algorithm SAC \
    --universe gym \
    --domain HalfCheetah \
    --task v2 \
    --exp-name my-sac-experiment-1 \
    --checkpoint-frequency 1000
```

Produces an error from tensorflow_probability trying to convert a Tensor to a numpy array.

However, downgrading to tensorflow 2.2.0 and tensorflow_probability 0.10.0 solves it: `pip install --upgrade --force-reinstall tensorflow_probability==0.10.0 tensorflow==2.2.0 cloudpickle==1.4.0`

**Comment by hartikainen** [comment]
Thanks for reporting this! I just pushed fixes for these. I think the underlying issue was not converting variales to tensors in the SAC methods. That's changed here: https://github.com/rail-berkeley/softlearning/pull/171/files#diff-c427dfbb58b5337d68da626b8e4cbd3324fb1836da0ca03e40cb9be61520c9ddR151-R153. Fixed in #171.
