### ISSUE TITLE
Using log_alpha in alpha loss

### ISSUE THREAD

**Issue by acohen13** [rail-berkeley/softlearning#37]
Why does the objective for alpha use log_alpha instead of alpha?
https://github.com/rail-berkeley/softlearning/blob/125ee6ee137145947703018e9980d064c94b1666/softlearning/algorithms/sac.py#L278
Is this equivalent to the objective in the paper which uses alpha or am I missing something?

Thank you for making this code publicly available.

**Comment by zhihanyang2022** [comment]
@hartikainen  Thanks for the short math derivation. I think it shows that the minimum value of the problem is unchanged if we use log_alpha instead of alpha. From hindsight, this is rather intuitive because alpha and log_alpha are both real numbers from negative infinity to positive infinity.

However, this is still something that I don't understand at first. When using alpha as a multiplier for sample entropy in the calculation of target and policy loss, we need to take the exp of log_alpha to get alpha. But this seems a little shaky, right? Given that log_alpha and alpha are equal in the derivation you presented.

Here's a perhaps naive explanation that I came up with:

```
min E[- log_alpha * log_pi - alpha * H_targ]
= min log_alpha * (E[-log_pi] - H_targ)
= min log_alpha * (H_curr - H_targ)
```

- If `H_curr - H_targ > 0`,  minimum is achieved by setting `log_alpha < 0`. This translates to an alpha between [0, 1] (trying taking exp of log_alpha), which lessens the entropy maximization behavior when updating networks.
- If `H_curr - H_targ < 0`,  minimum is achieved by setting `log_alpha > 0`. This translates to an alpha greater than 1, which strengthens the entropy maximization behavior when updating networks.
