### ISSUE TITLE
MultivariateNormalDiag log_prob with target_entropy and alpha

### ISSUE THREAD

**Issue by acohen13** [rail-berkeley/softlearning#47]
Thank you for sharing the code.

For Gaussian policies, in this implementation as well as the original SAC repository, the log_prob method of the MultivariateNormalDiag class is used to compute the log probability of an action.  This method returns the probability density and not the probability so log probabilities can be greater than 0.  The issues arise in the learning objective for alpha.  I can set a target_entropy = 0.0 in which you'd expect alpha to go to 0 (an entropy of 0 indicates a deterministic policy) but this is not the case since log_pi can be greater than or less than 0.

Is there something simple I'm missing here?

Thank you again.

**Comment by haarnoja** [comment]
Thanks for your question. Since we consider only continuous actions in this code base, we deal with *differential entropy* that can also get negative values. In fact, we found that a target (differential) entropy equal to the negative of the number of action dimensions (for example -6 for HalfCheetah) works well across different environments. Hope this answers your question!

**Comment by acohen13** [comment]
Yes this clarifies everything.  Thank you very much for the response!
