### ISSUE TITLE
Unable to reproduce result on HalfCheetah-v2

### ISSUE THREAD

**Issue by quanvuong** [rail-berkeley/softlearning#75]
I am unable to obtain the result as reported in the paper on the openai environment HalfCheetah-v2. The commit used to obtain this result is 1f6147c83b82b376ceed5e95df5a422113741468, which isn't too long ago. The result is averaged over 5 random initial seeds.

![halfcheetah](https://user-images.githubusercontent.com/6988600/56314505-302ad400-614d-11e9-83bd-367f0b3bbeab.PNG)

Do you know what might be causing this issue? Thank you!

I am able to obtain the result as reported (or close to it) in the paper on the remaining environments, posted here for reference. 

![ant](https://user-images.githubusercontent.com/6988600/56314532-42a50d80-614d-11e9-884e-a371ebbf8118.PNG)
![walker](https://user-images.githubusercontent.com/6988600/56314533-433da400-614d-11e9-8764-5a0bf902881c.PNG)
![humanoid](https://user-images.githubusercontent.com/6988600/56314534-433da400-614d-11e9-99a5-2ad69491d884.PNG)
![hopper](https://user-images.githubusercontent.com/6988600/56314535-433da400-614d-11e9-8e2e-31e6a16a2d06.PNG)

**Comment by hartikainen** [comment]
Thanks a lot for reporting this! This is not expected, and it's not immediately obvious to me what might cause it. Just to make sure: are all these figures produced with the default values in the `variants.py`? How many seeds are in each figure?

**Comment by quanvuong** [comment]
yup, the figures are produced with the default values in variants.py.

The results in each figure are averaged over 5 random initial seeds.

**Comment by hartikainen** [comment]
Thanks! I'll try to look into this soon.

**Comment by hartikainen** [comment]
Hey, I just ran HalfCheetah from the latest master, and unfortunately cannot reproduce the problems you're seeing. Here are the results I see across 6 seeds:
![newplot (77)](https://user-images.githubusercontent.com/2308543/57184787-8bf79b80-6e75-11e9-8fd2-24b4cd857701.png)
![newplot (78)](https://user-images.githubusercontent.com/2308543/57184792-9c0f7b00-6e75-11e9-940f-77eb55e29a55.png)

The results are a tiny bit worse than what we report in our paper [1], maybe because of the upgrade from mujoco 1.5 to 2.0.

Maybe there's something different in your environment? Could you post the output of `pip freeze`? Also, which mujoco version are you using?

[1] https://arxiv.org/pdf/1812.05905.pdf

**Comment by quanvuong** [comment]
Thank you for your comment!

I will rerun master and let you know how it goes here.

**Comment by quanvuong** [comment]
Thank you for your effort in maintaining the repo. It has been super useful and illuminating to read the code. Also, thank you for rerunning the master and helps me get to the bottom of my issue. Please find my results below:

Running the master on 5th May, which corresponds to commit 1f6686d765052c874dcf28f8036acde742decd79 does not reproduce the reported results. This is because in my runs, 1 out of 5 is significantly worse than the other runs. The performance graph is shown below.

![HalfCheetah_evaluation_return-average_long_title_True_plot_individual](https://user-images.githubusercontent.com/6988600/57570058-d341d700-73f5-11e9-95d3-f8b7524c900a.png)

However, you might not be able to reproduce this result by setting the initial seeds to the values in my runs. This is because of this issue https://github.com/rail-berkeley/softlearning/issues/80.

After I also set the seed of the environment and fix the value for the initial seeds in the runs, I obtained similar results where some of the runs are significantly worse than others.

![HalfCheetah_training_return-average_long_title_True_plot_individual](https://user-images.githubusercontent.com/6988600/57570141-beb20e80-73f6-11e9-88f8-a26bb2b166da.png)

![HalfCheetah_evaluation_return-average_long_title_True_plot_individual](https://user-images.githubusercontent.com/6988600/57570144-c2de2c00-73f6-11e9-9d6d-f519a82611c4.png)

The output of pip freeze can be found in the file below

[output.txt](https://github.com/rail-berkeley/softlearning/files/3169057/output.txt)

I am using mujoco 1.50 for Linux.

**Comment by hartikainen** [comment]
Thanks for the detailed response! This still seems a little odd since I'm not able to get any seeds failing like that.

One difference I see in your `pip freeze` output is the mujoco-py version. You have `mujoco-py==1.50.1.68` whereas we recently upgraded to `mujoco-py==2.0.2.0`. Could you try running `pip install -U gym mujoco-py` and [installing mujoco 2.0](https://www.roboti.us/index.html), and see if that solves the issue?

**Comment by Nicolinho** [comment]
I also observed very similar results as @quanvuong did (including runs that converged at ~2k return). I used mujoco 2.0 and mujoco-py 2.0.2.0.

**Comment by hartikainen** [comment]
@Nicolinho would you mind pasting the output of your `pip freeze` and `conda list` here?

**Comment by Nicolinho** [comment]
@hartikainen 
[pip_freeze.txt](https://github.com/rail-berkeley/softlearning/files/3194870/pip_freeze.txt)
[conda_list.txt](https://github.com/rail-berkeley/softlearning/files/3194871/conda_list.txt)

**Comment by hartikainen** [comment]
Hey @quanvuong and @Nicolinho, thanks a lot for providing the information. I spent a bit of time debugging this today. I couldn't find anything obvious that could be wrong, but was eventually able to reproduce this issue on one of my machines. The weird thing is that still on other machines, the cheetah runs completely fine; I ran a total of 30 seeds on 3 different machines and none of them had the issue. 10 of those seeds are found from a comment in the latest PR: https://github.com/rail-berkeley/softlearning/pull/85#issuecomment-493781948.

I'll try to dig deeper soon and let you know if I find anything.

**Comment by hartikainen** [comment]
Looks like the policy for some reason flips around in the beginning and thus gets stuck to a local minimum:
![output](https://user-images.githubusercontent.com/2308543/57993919-d11fee00-7a6f-11e9-80ea-b5493f1ae68b.gif)

**Comment by quanvuong** [comment]
It was so satisfying to finally know why this happened. Thank you for the investigative work!

**Comment by szrlee** [comment]
> Hey, I just ran HalfCheetah from the latest master, and unfortunately cannot reproduce the problems you're seeing. Here are the results I see across 6 seeds:
> ![newplot (77)](https://user-images.githubusercontent.com/2308543/57184787-8bf79b80-6e75-11e9-8fd2-24b4cd857701.png)
> ![newplot (78)](https://user-images.githubusercontent.com/2308543/57184792-9c0f7b00-6e75-11e9-940f-77eb55e29a55.png)
> 
> The results are a tiny bit worse than what we report in our paper [1], maybe because of the upgrade from mujoco 1.5 to 2.0.
> 
> Maybe there's something different in your environment? Could you post the output of `pip freeze`? Also, which mujoco version are you using?
> 
> [1] https://arxiv.org/pdf/1812.05905.pdf

Hi @hartikainen , for the curve of one single trial, do you use smoothed curve?
My reproduction is not very stable. This is plotted by tensorboard with smooth=0.6. Each curve is from one random seed.

![halfcheetah-v2_5-seeds_ray_tune_evaluation_episode-reward-mean](https://user-images.githubusercontent.com/6252426/59108681-19934300-896e-11e9-812b-5bbf9959b65f.png)

Thanks!

**Comment by hartikainen** [comment]
@szrlee yeah, my figures were smoothed with [viskit](https://github.com/vitchyr/viskit)'s default smoothing.

**Comment by amiranas** [comment]
I think the problem is that Gym has two separate random seeds for an environment. One is set during the creation of the environment. The other is the seed of `env.action_space`. The second seed is responsible for the random actions of `env.action_space.sample()`. For some reason the action space seed is different from the main seed. Moreover, in many gym versions the action space seed is always set to 0. I'm not certain what the current gym version does, but just to be sure I always set the action space seeds myself. 

I run some SAC experiments with a current gym version and first set the action space seed to zero by adding the following line to the [`GymAdapter`](https://github.com/rail-berkeley/softlearning/blob/master/softlearning/environments/adapters/gym_adapter.py#L73) class:

    env = gym.envs.make(env_id, **kwargs)
    env.action_space.seed(0)

The result after 1 mil timesteps was similar to those shown above:

![0_seed](https://user-images.githubusercontent.com/38289485/60045459-372e0f80-96c5-11e9-9379-15bd4a199a0f.png)

Then I rerun the experiment with a random action space seed:

    env = gym.envs.make(env_id, **kwargs)
    env.action_space.seed(int.from_bytes(os.urandom(4), byteorder='big'))

It made 3 of the 9 runs get stuck at the back-flip policy:

![rand_seed](https://user-images.githubusercontent.com/38289485/60045502-562ca180-96c5-11e9-8a11-92aa23a76bf0.png)

This problem seems to be gone when I increase the amount of random steps in the beginning of training (`n_initial_exploration_steps`) to 10000 steps. The result for 9 runs with random action space seeds was:

![rand_seed_long_init](https://user-images.githubusercontent.com/38289485/60045693-c20f0a00-96c5-11e9-914a-bcbd724e6c7d.png)


Gym commit: 98917cf
SAC commit: b4db23a
Mujoco py: a1b6e31
Mujoco 2.0

**Comment by xanderdunn** [comment]
I was able to readily reproduce the paper's results on HalfCheetah-v2 without changing any defaults:
<img width="671" alt="Screen Shot 2021-02-23 at 08 06 41" src="https://user-images.githubusercontent.com/1313618/108871495-114dc200-75ae-11eb-85fa-8c7f448072a6.png">
All four seeds achieve >15,000 evaluation mean reward on the first 3M timesteps. 10.7 hours of simultaneous compute on 2x A100s. These seed values were also set on `env.action_space.seed()` and `env.seed()` as @amiranas described.

MuJoCo 2.0
softlearning 46f14436f62465a02b99f431bbcf57a7fa0fd09d

**Comment by hartikainen** [comment]
Nice, thanks a ton for reporting these @xanderdunn! Seems like this issue can be closed now.
