### ISSUE TITLE
How to use gym environment ?

### ISSUE THREAD

**Issue by starimpact** [rail-berkeley/softlearning#9]
I want to use sac in the gym environment, such as SpaceInvaders.
How to do it?

**Comment by hartikainen** [comment]
Generally, in order to use gym environments, you would add a new field in https://github.com/rail-berkeley/softlearning/blob/88f601968c337f9ee76207c9d3c403b750acc4ad/softlearning/environments/adapters/gym_adapter.py#L39, and then use it by changing the `--domain` and `--task` options in the run script (e.g. `python -m examples.development.main ... --domain=Swimmer --task=v2`).

However, our SAC implementation doesn't currently support discrete actions, which is why you cannot run `SpaceInvaders` at the moment. I've heard someone else asking support for discrete actions before, and it might be worth implementing at some point.

Anyway, I think we should support arbitrary gym domains and tasks. I created a new issue to track it's implementation: #10
